DROP DATABASE IF EXISTS msds;
CREATE DATABASE msds;

DROP TABLE IF EXISTS catalog;

\c msds;

CREATE TABLE  catalog(
    CID VARCHAR(10) PRIMARY KEY NOT NULL,
    CNAME VARCHAR(100),
    CPREREQ VARCHAR(10)
);
