version: '3.7'

services:
  go-app:
    container_name: go-app
    image: nufde/assignment-6-go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=msds sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msds
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}